import os
import logging
from pathlib import Path
from typing import Tuple
from fpdf import FPDF
from app.config import EXPORTS_DIR
from app.models import ComicLayout

logger = logging.getLogger(__name__)

def _clean_text(text: str) -> str:
    """Sanitizes unicode punctuation to prevent FPDF latin-1 encoding errors."""
    if not text:
        return ""
    replacements = {
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2014": "--",
        "\u2013": "-",
        "\u2026": "...",
        "\u00a0": " ",
        "’": "'",
        "“": '"',
        "”": '"',
        "—": "--",
        "–": "-",
        "…": "..."
    }
    for orig, rep in replacements.items():
        text = text.replace(orig, rep)
    return text.encode("latin-1", "replace").decode("latin-1")


class ComicPDF(FPDF):
    """Custom FPDF layout engine tailored for comic books."""

    def __init__(self, title: str):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.comic_title = _clean_text(title)
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        # Draw header banner only on page 1
        if self.page_no() == 1:
            self.set_fill_color(255, 208, 39)  # Comic Yellow
            self.rect(10, 8, 190, 18, "FD")
            self.set_draw_color(21, 21, 34)
            self.set_line_width(0.8)
            self.rect(10, 8, 190, 18)

            self.set_font("Helvetica", "B", 16)
            self.set_text_color(21, 21, 34)
            self.set_xy(12, 10)
            self.cell(186, 7, f"COMICCRAFT: {self.comic_title.upper()}", align="C")
            self.ln(7)

            self.set_font("Helvetica", "I", 9)
            self.set_text_color(80, 80, 80)
            self.cell(186, 5, "Official AI Sequential Graphic Edition -- Generated by ComicCraft", align="C")
            self.ln(6)
        else:
            self.set_font("Helvetica", "B", 8)
            self.set_text_color(120, 120, 120)
            self.set_xy(10, 8)
            self.cell(190, 5, f"COMICCRAFT: {self.comic_title.upper()} | PAGE {self.page_no()}", align="R")
            self.ln(6)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(140, 140, 140)
        self.cell(0, 8, f"ComicCraft AI Comic Creator - Page {self.page_no()}", align="C")


def export_comic_to_pdf(layout: ComicLayout) -> Tuple[str, str]:
    """
    Compiles a ComicLayout into an A4 vector PDF document with custom panels,
    dialogue callouts, and narration banners.
    Returns (relative_web_url, absolute_file_path).
    """
    pdf_filename = f"{layout.comic_id}.pdf"
    pdf_path = EXPORTS_DIR / pdf_filename

    pdf = ComicPDF(title=layout.title)
    pdf.add_page()

    # Story metadata summary bar on Page 1
    pdf.set_fill_color(245, 245, 250)
    pdf.set_draw_color(200, 200, 210)
    pdf.set_line_width(0.3)
    pdf.rect(10, 32, 190, 10, "FD")

    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(30, 30, 40)
    pdf.set_xy(12, 33)
    meta_text = (
        f"HERO: {_clean_text(layout.character_name)}  |  "
        f"WORLD: {_clean_text(layout.setting)}  |  "
        f"TONE: {_clean_text(layout.tone)}  |  "
        f"STYLE: {_clean_text(layout.art_style)}"
    )
    pdf.cell(186, 8, meta_text, align="L")
    pdf.ln(12)

    # Render Panels
    for panel in layout.panels:
        if pdf.get_y() > 210:
            pdf.add_page()

        panel_top = pdf.get_y()

        # 1. Panel Header & Title
        pdf.set_fill_color(21, 21, 34)  # Comic Black
        pdf.rect(10, panel_top, 190, 7, "FD")
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(255, 208, 39)  # Yellow
        pdf.set_xy(12, panel_top + 1)
        pdf.cell(186, 5, f"PANEL {panel.panel_number}: {_clean_text(panel.title).upper()}", align="L")
        pdf.ln(7)

        # 2. Narration Box (Pale Yellow Caption)
        if panel.narration:
            narr_y = pdf.get_y()
            pdf.set_fill_color(255, 249, 210)  # Caption Yellow
            pdf.set_draw_color(21, 21, 34)
            pdf.set_line_width(0.4)
            pdf.rect(10, narr_y, 190, 9, "FD")

            pdf.set_font("Helvetica", "I", 8.5)
            pdf.set_text_color(30, 30, 30)
            pdf.set_xy(13, narr_y + 1.5)
            pdf.cell(184, 6, _clean_text(panel.narration[:130]), align="L")
            pdf.ln(10)

        # 3. Main Panel Body: Image on Left (55mm x 55mm), Dialogue on Right
        body_y = pdf.get_y()
        img_placed = False

        if panel.local_image_path and os.path.exists(panel.local_image_path):
            try:
                pdf.set_draw_color(21, 21, 34)
                pdf.set_line_width(0.6)
                pdf.rect(12, body_y, 55, 55)
                pdf.image(panel.local_image_path, x=12, y=body_y, w=55, h=55)
                img_placed = True
            except Exception as e:
                logger.warning(f"Failed to render panel image in PDF: {e}")

        # Dialogue and Sound Effect Section (Right side)
        right_x = 72 if img_placed else 12
        right_w = 128 if img_placed else 186

        # Sound Effect Banner
        if panel.sound_effect:
            pdf.set_xy(right_x, body_y + 2)
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(230, 40, 40)  # Comic Action Red
            pdf.cell(right_w, 6, f"<< *{_clean_text(panel.sound_effect)}* >>", align="L")

        # Dialogue Speech Bubble Box
        bubble_y = body_y + 12
        pdf.set_fill_color(255, 255, 255)
        pdf.set_draw_color(21, 21, 34)
        pdf.set_line_width(0.5)
        pdf.rect(right_x, bubble_y, right_w - 4, 26, "FD")

        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(21, 21, 34)
        pdf.set_xy(right_x + 3, bubble_y + 2)
        pdf.cell(right_w - 10, 5, "SPEECH:", align="L")

        pdf.set_font("Helvetica", "", 8.5)
        pdf.set_xy(right_x + 3, bubble_y + 8)
        clean_dlg = _clean_text(panel.dialogue)
        pdf.multi_cell(right_w - 10, 4.5, clean_dlg)

        # Scene description snippet
        pdf.set_font("Helvetica", "I", 7)
        pdf.set_text_color(110, 110, 110)
        pdf.set_xy(right_x, body_y + 44)
        scene_summary = f"Visual Prompt: {_clean_text(panel.visual_prompt[:95])}..."
        pdf.cell(right_w, 5, scene_summary, align="L")

        pdf.set_y(body_y + 60)
        pdf.ln(4)

    # Save output PDF
    pdf.output(str(pdf_path))
    logger.info(f"Successfully compiled PDF comic to {pdf_path}")

    return f"/static/exports/{pdf_filename}", str(pdf_path)

