from typing import List, Optional
from pydantic import BaseModel, Field

class ComicStoryRequest(BaseModel):
    """Input payload submitted to generate an AI comic."""
    story_prompt: str = Field(..., description="High-level creative narrative premise")
    character_name: str = Field("Max", description="Name of the main character / protagonist")
    setting: str = Field("Neo Metropolis", description="World or environment where story takes place")
    tone: str = Field("Adventurous", description="Emotional tone or genre of the comic")
    art_style: str = Field("Classic Comic Book", description="Visual aesthetic for illustrations")
    panel_count: int = Field(5, ge=1, le=10, description="Number of panels to generate (default 5)")

class PanelOutline(BaseModel):
    """Structured outline item generated by Gemini Flash."""
    panel_number: int
    title: str
    scene_description: str
    visual_prompt: str

class EnrichedPanel(BaseModel):
    """Full comic panel enriched with dialogue and narration by Gemini Pro."""
    panel_number: int
    title: str
    scene_description: str
    visual_prompt: str
    narration: str
    dialogue: str
    sound_effect: str = "POW!"
    image_url: Optional[str] = None
    local_image_path: Optional[str] = None

class ComicLayout(BaseModel):
    """Complete assembled comic strip layout representation."""
    comic_id: str
    title: str
    character_name: str
    setting: str
    tone: str
    art_style: str
    panels: List[EnrichedPanel]
    created_at: str
    pdf_path: Optional[str] = None
    download_url: Optional[str] = None

class TestImageRequest(BaseModel):
    """Request model for testing image generation."""
    prompt: str = Field(..., description="Custom visual prompt to synthesize")
    art_style: str = Field("Classic Comic Book", description="Art style filter")

class TestImageResponse(BaseModel):
    """Response model for image generation diagnostic test."""
    status: str
    image_url: str
    prompt_used: str
    generation_mode: str

